version: '3.8'

services:
  app:
    image: 831926627674.dkr.ecr.ap-northeast-2.amazonaws.com/tourgether-server
    container_name: tourgether-app
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgis/postgis:15-3.3
    container_name: prod-postgis-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    volumes:
      - ./pgdata/prod:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: prod-redis-db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata/prod:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
