version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: dev-postgis-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - ./pgdata/dev:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: dev-redis-db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata/dev:/data
